# Site settings
title: Javier Daza
email: your-email@gmail.com
description: La página personal y portafolio de Javier Daza, desarrollador web en Python y Django.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://javierdaza.co" # the base hostname & protocol for your site
twitter_username: xavidaza
paginate: 5
paginate_path: "/blog/pagina:num/"

# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Javier Daza
      layout: "post"
      comments: true

#Sass settings
sass:
    sass_dir: assets/scss